---
- name: Sending an e-mail from kai@kionetworks.com
  vars:
    # Credenciales
    user: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              62383032353739366566353732623834666464343730346536646636306539303266633563316232
              3634323836386564623331353534373936393965383630350a396232656534623735616662623233
              32636162363538303131623432373332323335396335316162653836613838613661643538333762
              6164616161643531320a316431373730323839383935333230313434393434396438646132323831
              63343939383934386563393835356635373238356561386634336565663566616265
    pwd: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              30653136336135383039353836376332346432336538633136393835303162623061356433343764
              3331393638643530623564356335623934643935663332310a343363323063336661613635366463
              34623834323063336666616638356336326537363335326632613833633465316134346262316232
              3935616532376539360a336261396435666264346339636138653035633765353336363536333362
              64656137346535643163616632363462323934373838636262306663303231623161
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ user }}"
    password: "{{ pwd }}"
    to: "{{ para | default([]) }}"
    cc: "{{ conCopia | default([]) }}"
    subject: "{{ asunto | default([]) }}"
    body: "{{ mensaje | default([]) }}"
    attach: "{{ adjuntos | default([]) }}"
  delegate_to: localhost


#Author Erick Benitez